// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emvoksnsvctdvwodwclw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtdm9rc25zdmN0ZHZ3b2R3Y2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTk2NDUsImV4cCI6MjA2NTQ5NTY0NX0.-pKM0yoqMZtQsa-VVozdkVfmK9DUgdWRFetEH9u27PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);