// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvqrgcodojkifpaivdqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cXJnY29kb2praWZwYWl2ZHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTQ2MDksImV4cCI6MjA2NDk5MDYwOX0.4QiY3xJdf5DQtM2ZXGwy4Qhv2bCdemPfBwkzTmu2dic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);